////////////////////////////// RENDER.COM ////////////////////////////////

### GET all Users

GET https://byui-cse-341-groupjasnah.onrender.comuser HTTP/1.1

### DELETE user

DELETE https://byui-cse-341-groupjasnah.onrender.com/user/Elizabeth HTTP/1.1

### user1
POST https://byui-cse-341-groupjasnah.onrender.com/user HTTP/1.1
Content-Type: application/json

{
  "username": "Elizabeth",
  "password": "elizabethtellez@12345",
   "firstName": "Elizabeth",
   "lastName": "Tellez",
   "email": "elizabeth@cse341.com"
}

### user1 update### PUT user 
PUT https://byui-cse-341-groupjasnah.onrender.com/user/Elizabeth HTTP/1.1
content-type: application/json

{
  "username": "Elizabeth",
  "password": "elizabethtellez@12345",
   "firstName": "Elizabeth",
   "lastName": "Tellez",
   "email": "elizabeth@hotmail.com",
   "phoneNumber": "63453958",
   "country": "Mexico",
   "city": "Iztapalapa",
   "birthday": "09/11/1985",
   "address": "7095 Woodbine Ave, Iztapalapa"
}


////////////////////////////// LOCALHOST USER ////////////////////////////////

###GET all Users

GET http://localhost:8080/user HTTP/1.1

### DELETE user

DELETE http://localhost:8080/user/Owas HTTP/1.1


### user2

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
  "username": "Owas",
  "password": "Owas@12345",
   "firstName": "Owamamwen",
   "lastName": "Ogunniyi",
   "email": "owas@cse341.com"
}
###
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
  "title": "HELLO",
  "content": "Hello",
   "status": "Active"
}

### user2 update### PUT user 

PUT http://localhost:8080/user/Owas HTTP/1.1
content-type: application/json

{
  "username": "Owas",
  "password": "Owas@12345",
   "firstName": "Owamamwen",
   "lastName": "Ogunniyi",
   "email": "owas@yahoo.com",
   "phoneNumber": "453563635",
   "country": "France",
   "city": "Paris",
   "birthday": "12/11/1991",
   "address": "Delta, 48 Boulevard Jourdan, 75014 Paris"
}


### user3

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
  "username": "Ariel",
  "password": "Ariel@12345",
   "firstName": "Ariel",
   "lastName": "Perez",
   "email": "ariel@cse341.com"
}

### user3 update### PUT user 

PUT http://localhost:8080/user/Owas HTTP/1.1
content-type: application/json

{
  "username": "Ariel",
  "password": "Ariel@12345",
   "firstName": "Ariel",
   "lastName": "Perez",
   "email": "ariel@cse341.com",
   "phoneNumber": "135363635",
   "country": "USA",
   "city": "Idaho",
   "birthday": "08/09/1989",
   "address": "205 N 500 W"
}


### user4

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
  "username": "Alexis",
  "password": "alexis@12345",
   "firstName": "Alexis",
   "lastName": "Ortiz",
   "email": "alexis@cse341.com"
}

### PUT user4 updated 

PUT http://localhost:8080/user/Owas HTTP/1.1
content-type: application/json

{
  "username": "Alexis",
  "password": "alexis@12345",
   "firstName": "Alexis",
   "lastName": "Ortiz",
   "email": "alexis@cse341.com",
   "phoneNumber": "453563635",
   "country": "USA",
   "city": "Idaho",
   "birthday": "08/10/1988",
   "address": "205 N 500 W"
}


###User1 make a post

POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "title": "can you assign 2 classes to a single html element",
    "content": "I want to style html elements in CSS using class, not id. and I need to assign 2 classes to 1 element. I want one mother class e.g.'animal' and smaller classes e.g. 'mammal' & 'reptile'. I could just style every element in the smaller classes individually with id's but I'm working on a big project and that would take forever. is there a way to assign two classes to 1 element?", 
    "status": "Active",
    "categories": {
        "_id": "640aa7200a55706f4a3b0d87"
    },
    "users": {
        "_id": "640aa7360a55706f4a3b0d8a",
        "firstName": "Elizabeth"
    }
}

###GET all Posts

GET http://localhost:8080/post HTTP/1.1

###User2 make a comment

POST http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, you can easily give multiple classes to a single element, just separate them by a space. For example: <div class=animal mammal reptile>...</div> Now the above div has 3 classes, animal, mammal and reptile. And now you can target each just like you'd target a single class. ",    
    "posts": {
        "_id": "640aa7fe0a55706f4a3b0d95"
    },
    "users": {
        "_id": "640aa73c0a55706f4a3b0d8c",
        "firstName": "Owas"
    }
}

###User3 make a comment to the user1 post

POST http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, just simply add a space after the first class and add another.",    
    "posts": {
        "_id": "640aa7fe0a55706f4a3b0d95"
    },
    "users": {
        "_id": "640aa7440a55706f4a3b0d8e",
        "firstName": "Ariel"
    }
}

###User4 make a correction on the comment from user3

PUT http://localhost:8080/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "Yes, just simply add a space after the first class and add another.",    
    "posts": {
        "_id": "640aa7fe0a55706f4a3b0d95"
    },
    "users": {
        "_id": "640aa7460a55706f4a3b0d90",
        "firstName": "Alexis"
    }
}

###GET all Comments

GET http://localhost:8080/comments HTTP/1.1




